#!/bin/bash -x

UPDATE_FILE="${1:-/var/lib/bbctrl/firmware/update.tar.bz2}"
if [ -e "$UPDATE_FILE" ]; then
  echo /usr/local/bin/update-from-file "$UPDATE_FILE"
  exit $?
fi

export UPDATE=/var/lib/bbctrl/firmware/update.tar.bz2

if [ ! -e "$UPDATE" ]; then
      echo "Missing $UPDATE"
      exit 1
    fi
    if [ -e "$UPDATE" ]; then
      echo /usr/local/bin/update-from-file "$UPDATE"
      exit $?
    fi
fi

